-- liquibase formatted sql

-- changeset ssapyanov:1
CREATE TABLE dynamic_rules (
                               id UUID PRIMARY KEY NOT NULL,
                               product_name VARCHAR(255) NOT NULL,
                               product_id UUID NOT NULL,
                               product_text VARCHAR(1000) NOT NULL
);

CREATE TABLE query_conditions (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                  query VARCHAR(255) NOT NULL,
                                  negate BOOLEAN NOT NULL,
                                  rule_id UUID,
                                  CONSTRAINT fk_condition_rule FOREIGN KEY (rule_id) REFERENCES dynamic_rules(id)
);

CREATE TABLE query_arguments (
                                 condition_id BIGINT,
                                 argument VARCHAR(255) NOT NULL,
                                 CONSTRAINT fk_argument_condition FOREIGN KEY (condition_id) REFERENCES query_conditions(id)
);