spring.application.name=recommendation-service
application.recommendations-db.url=jdbc:h2:file:./transaction;IFEXISTS=FALSE
spring.sql.init.mode=never
spring.datasource.url=jdbc:postgresql://localhost:5432/rules_db
spring.datasource.username=rec_user
spring.datasource.password=1231234As
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/master.yaml
telegram.bot.token=8649767943:AAHoNJOt9WwDYmVT9aBLUvuMF-7C3FS5xiA
spring.liquibase.drop-first=false